apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: nginx-controller
type: Opaque
data: 
  REACT_APP_API_KEY: QUl6YVN5QVdOMGU2VUtVZjI2ZEtTb3hyTlY5TFhSYS1VUHIySG40
  REACT_APP_AUTH_DOMAIN: cmFmZmxlLXNob3BwaW5nLWY4NWU2LmZpcmViYXNlYXBwLmNvbQ==
  REACT_APP_PROJECT_ID: cmFmZmxlLXNob3BwaW5nLWY4NWU2
  REACT_APP_STORAGE_BUCKET: cmFmZmxlLXNob3BwaW5nLWY4NWU2LmFwcHNwb3QuY29t
  REACT_APP_MESSAGING_SENDER_ID: NjU3NTM2NzU0MzEw
  REACT_APP_APP_ID: MTo2NTc1MzY3NTQzMTA6d2ViOjRiYjhiZTMzOGExZDJiNDY2YmU3MDc=
  REACT_APP_MEASUREMENT_ID: Ry04MlM4MFdRWThT